### ISSUE TITLE
사진 촬영 기능 구현

### ISSUE THREAD

**Issue by imlimchill** [imlimchill/PhotoApplication#2]
1. UI 
사진 촬영을 할 때 카메라 화면의 비율이 3:4가 되도록 한다.

2. 기능 구현
1) 메인화면에 미리보기 view가 보여야한다.
2) 사진 촬영버튼을 눌렀을 때 사진이 찍혀야 한다. 
3) 사진이 찍히면 파일에 저장이 되야한다.
     파일이름은 'mrPhoto'로 하고 만약 해당 파일 이름이 없으면 그 파일을 생성한 후에 저장한다.

**Comment by dasol-jeong** [comment]
#10 개발 완료
